Update de_de.json
NoRiskClient/translations pull request #2
Opened 2024-07-01 00:01 UTC by brentspine

2024-07-03 09:50 UTC, SirKnubble requested changes
Related to [Issue #215](https://github.com/NoRiskClient/issues/issues/215)

- Add below `"nrc.friends.host.invite_friend" : "In die Welt einladen",`:
```
  "nrc.friends.host.invite_request" : "Du wurdest von %s in eine Welt eingeladen",
```

- Add below `"nrc.ui.modules.value.showHelmet" : "Helm anzeigen",`:
```
  "nrc.ui.modules.value.showInF3" : "In F3 anzeigen",
  "nrc.ui.modules.value.showInTab" : "In Tab-Liste anzeigen",
```

2024-07-05 09:35 UTC, SleepyPxnda commented
Linked to https://github.com/NoRiskClient/issues/issues/215

2024-07-23 19:41 UTC, SleepyPxnda requested changes

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "mcreal.browse.label.your_turn" : "Klicke hier, um der erste zu sein, der einen McReal postet!",
"ein"

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "mcreal.post.delete.request" : "Bist du sicher, dass du deinen Beitrag löschen wirst?",
Bist du sicher, dass du deinen Beitrag löschen willst?

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "mcreal.upload.show_others" : "[Andere anzeigen]",
Warum mit "[" und "]" ?

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "norisk.cosmetics.outfit.toast.cosmeticsettings.saved" : "Kosmetik Einstellungen Gespeichert.",
Kosmetik Einstellungen gespeichert.

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "norisk.screenshot.action.upload" : "[Hochladen]",
Warum mit "[" und "]" ?

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "norisk.screenshot.copy.success" : "Screenshot in Zwischenablage kopiert",
Screenshot wurde in die Zwischenablage kopiert

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "nrc.cosmetics.ui.unowned_items_dialog_closed_title" : "GEGENSTÄNDE, DIE NICHT IM BESITZ SIND, SIND AUSGESTATTET...",
Sicher das wir hier alles in Caps wollen ?

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "nrc.friends.host.hosting_success_friends_invite_info_copy_url" : "[URL kopieren]",
Klammern ?

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "nrc.friends.offline.seconds" : "Offline für %s Sekunden",
Offline seit ...

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "nrc.friends.tab.outgoing" : "%s AUSSTEHEND",
Caps ?

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "nrc.friends.wheel.ui.rename_action" : "Umbenennen...",
Aktion umbennenen

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "nrc.friends.wheel.ui.rename_command" : "Umbenennen...",
Kommand umbennenen

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "nrc.ui.modules.value.mcRealTimeNotification" : "Echtzeitbenachrichtigung",
Hier geht es nicht um die "RealTimeNotification" sondern um die Benachrichtigung, dass du ein MCReal machen sollst 😆

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "nrc.ui.modules.value.mobs" : "Mobs",
Monster

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "nrc.ui.modules.value.pingScale" : "Ping-Skala",
Hier ist glaube eher die Skalierung gemeint

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "nrc.ui.modules.value.showCps" : "CPS anzeigen",
Eigentlich eher KPS wenn wir auf Deutsch bleiben wollen

2024-07-23 19:41 UTC, SleepyPxnda commented on de_de.json
> +  "nrc.ui.modules.value.showZ" : "Z anzeigen",
Vllt hier mit X-Koordinaten, Y-Koordinaten etc.

2024-07-23 19:41 UTC, SleepyPxnda requested changes
Generell vllt auch schauen ob du Sätze mit oder ohne Punkte machst, gut wäre es einheitlich.

2024-07-23 19:47 UTC, SleepyPxnda commented
@brentspine Mir wäre es auch lieb, wenn du vllt nicht unbedingt andere PRs kritisierst, solange du auch alles automatisiert machst 👍 Hättest du dir die nämlich mal durchgelesen, wäre dir auch aufgefallen, dass die Übersetzungen teilweise keinen Sinn machen 😄

2024-07-23 19:50 UTC, SleepyPxnda commented on de_de.json
> +  "mcreal.browse.label.discovery" : "Entdeckung",
Anderes Wort, das klingt giga arsch

2024-07-23 19:51 UTC, SleepyPxnda commented on de_de.json
> +  "mcreal.browse.label.friends" : "Meine Freunde",
"Freunde" reicht

2024-07-23 19:51 UTC, SleepyPxnda commented on de_de.json
> +  "mcreal.report.label.info" : "Was ist passiert?",
Hier vllt eher "Details" oder so

2024-07-23 21:42 UTC, brentspine commented
Danke. Ich schaue mir die Reviews morgen an. Viele Strings sind noch Überreste der alten Machine Translations.

2024-07-23 21:44 UTC, brentspine commented on de_de.json
> +  "norisk.screenshot.action.upload" : "[Hochladen]",
Wurde aus der Source übernommen (en_us.json). Ist für die Options im Screenshot Tool. 

Heißt: "Screenshot saved [Open] [Upload] [...]"

2024-07-23 21:45 UTC, brentspine commented on de_de.json
> +  "nrc.friends.host.hosting_success_friends_invite_info_copy_url" : "[URL kopieren]",
Generell für alle Optionen im Chat sind die Klammern im String mit eingenommen.

2024-07-23 21:46 UTC, brentspine commented on de_de.json
> +  "nrc.friends.tab.outgoing" : "%s AUSSTEHEND",
Aus Source übernommen

2024-07-23 21:48 UTC, brentspine commented on de_de.json
> +  "nrc.ui.modules.value.mcRealTimeNotification" : "Echtzeitbenachrichtigung",
Huch, die Line hab ich nicht gesehen. Vielen Dank

2024-07-23 21:49 UTC, brentspine commented on de_de.json
> +  "mcreal.upload.show_others" : "[Andere anzeigen]",
Aus Source übernommen. Klickbare Option im Chat

2024-07-23 21:51 UTC, brentspine commented on de_de.json
> +  "mcreal.report.label.info" : "Was ist passiert?",
Wollte möglichst nah am Source bleiben. Dort heißt es "What happened?"

2024-07-23 21:58 UTC, brentspine commented
Die Frage ist, ob wir auch an en_us Änderungen durchführen sollten. Ich stimme zu, dass Capslock in den Übersetzungen nicht unbedingt Sinn macht. Es ist zwar suboptimal, aber einfacher, als dass der Code geändert werden muss mit .toUpperCase(). Der Capslock war immerhin eine Designentscheidung, die länger bleiben wird.

2024-08-02 11:02 UTC, brentspine commented on de_de.json
> +  "nrc.ui.modules.value.mcRealTimeNotification" : "Echtzeitbenachrichtigung",
Ich hab kein BeReal, wie übersetzt man das am Besten? 

"Real Zeit Benachrichtigung" (Aus dem Englischen Source "Real Time Notification") klingt ziemlich beschissen meiner Meinung nach.
Ich habe jetzt "McReal Benachrichtigung" genommen.

2024-08-02 11:13 UTC, brentspine commented
Siehe
https://github.com/NoRiskClient/translations/pull/2/commits/fac55535e78175da1da9afa6cd0e4e460da92e2c
https://github.com/NoRiskClient/translations/pull/2/commits/16e5ce6f50584ad45acf7a70ef9450efdf376cb9

2024-08-02 23:21 UTC, merged